### ISSUE TITLE
The top 10 shows 11 movies 

### ISSUE THREAD

**Issue by rleroi** [BoredLama/stremio-top-10-torrentfreak#1] opened 2019-03-03 16:07 UTC
See title :)

**Comment by BoredLama** [comment] 2019-03-04 10:56
Yes, this can happen unfortunately, it's not a bug though..

If you check torrent freak's top 10 blog posts, they sometimes set the links to IMDB for the movies wrongly. They frequently forget to update the links from the previous top 10 post, or sometimes only change one IMDB link instead of 2 (each top element has 2 IMDB links, one on it's name, and one on it's rating)

What this add-on does is that it takes those IMDB links, filters out all duplicates and sets them as a catalog in Stremio.

Because of them not updating their IMDB links correctly, it can happen to see 7/10 items, or even more then 10, as that's the unique number of IMDB IDs the list has..

This is not something that can be fixed on the add-ons side, it just needs the authors of the top 10 posts to be more careful when they write it up.

**Closed as completed by BoredLama** 2019-03-04 10:56 UTC
